### ISSUE TITLE
This can't actually get most dates.

### ISSUE THREAD

**Issue by suddjian** [gavindinubilo/random-dilbert#1]
You're using `Date.getDay()` which returns the day of the week. What you want is `Date.getDate()`. Also, sometimes the random date function generates months and days that are 0, which don't exist on the Dilbert site. They need to be ++'d.

**Comment by suddjian** [comment]
I forked this for my own use case that has different requirements, and it's since diverged quite a bit, otherwise I'd fix it and open a pull request

**Comment by dinubs** [comment]
thanks for pointing out! I noticed it a bit ago, you can tell because it will show the current days comic much more often than others, this code is pretty old and to say the least, it's pretty gross, and hasn't been updated since I initially wrote it. 

If I were to rewrite it it'd probably be a full frontend app and use https://github.com/gavindinubilo/jam-api to get the comic
